name: build-mac

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm run prebuild -- --arch x64
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - run: pnpm run prebuild -- --arch arm64
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: upload binaries
        uses: actions/github-script@v6
        with:
          script: |
            const zip = require('cross-zip')
            
            const script = require('./scripts/upload-binaries.js');

            await script({
              github,
              context,
              core,
              zip
            }); 
