name: build-windows

on: push
# on: 
#   push:
#     branches:
#       - master

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - run: choco install python visualstudio2017-workload-vctools -y
      - run: npm config set msvs_version 2017 --global
      - run: npm install --verbose -g node-gyp
      - run: npm install -g prebuild
      - run: npm install --loglevel verbose
      - run: npm why node-gyp
      - run: prebuild -r electron -t 101 -t 103 -t 106 -t 107 --format --force-process-config -u ${env:GH_TOKEN}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}     
