name: build-mac

on: push

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install -g node-gyp
      - run: npm install
      - run: npm run prebuild:mac:x64
      # - run: npm run prebuild:mac:arm64
