name: build-windows

on: push

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - run: npm install --global --production windows-build-tools
      - run: npm install -g node-gyp
      - run: npm install
      - run: npm run prebuild
