name: build-linux

on: push
# on: 
#   push:
#     branches:
#       - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '2.7.x'
      - run: sudo apt-get install libxtst-dev libpng++-dev
      - run: npm install -g node-gyp
      - run: npm install -g prebuild
      - run: npm install --loglevel verbose
      - run: prebuild -r electron -t 101 -t 103 -t 106 -t 107 -u $GH_TOKEN
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
