name: build-linux

on: push
# on: 
#   push:
#     branches:
#       - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '2.7.x'
      - run: sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
      - run: sudo apt-get update
      - run: sudo apt-get install libxtst-dev libpng++-dev gcc-7 g++-7 -y
      - run: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 70 --slave /usr/bin/g++ g++ /usr/bin/g++-7
      - run: npm install --loglevel verbose
      - run: npm run prebuild -- -u $GH_TOKEN
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
