name: build-windows

on: push
# on: 
#   push:
#     branches:
#       - master

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - run: choco install python visualstudio2017-workload-vctools -y
      - run: npm config set msvs_version 2017 --global
      - run: npm install --verbose -g node-gyp
      - run: npm install -g prebuild
      - run: npm install
      - run: prebuild -r electron -t 97 -t 98 -t 99 -t 100 -t 101 -t 102 -t 103 -t 104 -u ${env:GH_TOKEN}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}     
