name: build-windows

on: push
# on: 
#   push:
#     branches:
#       - master

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - run: choco install python visualstudio2017-workload-vctools -y
      - run: npm config set msvs_version 2017 --global
      - run: npm install --loglevel verbose
      - run: npm run prebuild -u ${env:GH_TOKEN}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}     
